---
- hosts: all
  sudo: yes
  vars:
   apache_version: 2.6
   motd_warning: 'Apollo Formation Ansible Janvier 2018 '
   testserver: yes
  tasks:
    - name: update to latest httpd
      yum:
        name: httpd
        state: latest
      notify: restart httpd
    - name: copy the httpd config
      copy:
        src: files/httpd.conf
        dest: /etc/httpd/conf/httpd.conf
      notify: restart httpd
    - name: start htppd at boot
      service:
        name: httpd
        state: started
        enabled: yes

  handlers:
  - name: restart httpd
    service:
      name: httpd
      state: restarted