---
- hosts: all
  sudo: yes
  vars:
   apache_version: 2.6
   motd_warning: 'Apollo Formation Ansible Janvier 2018 '
   testserver: yes
  tasks:
    - name: setup a MOTD
      copy:
        dest: /etc/motd
        content: "{{ motd_warning }}"
